blog/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/create'

  get 'sessions/destroy'

  get 'home/show'

  get 'welcome/index'

  
    get 'auth/:provider/callback', to: 'sessions#create'
    get 'auth/failure', to: redirect('/')
    get 'signout', to: 'sessions#destroy', as: 'signout'

    resources :sessions, only: [:create, :destroy]
    resource :home, only: [:show]

  resources :articles
  root 'welcome#index'

end

blog/app/models/article.rb
class Article < ActiveRecord::Base
	validates :title, presence: true,
                    length: { minimum: 5 }
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	helper_method :current_user

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

end

blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def index
		@articles = Article.all
		end

	def show
    	@article = Article.find(params[:id])
  	end
	
	def new
    end
    
    def edit
  		@article = Article.find(params[:id])
	end



    def create
    	@article = Article.new(article_params)

	    if @article.save
    	  redirect_to @article
	    else
	      render 'new'
	    end

	end

	def update
		@article = Article.find(params[:id])

		if @article.update(article_params)
			redirect_to @article
		else
			render 'edit'
		end
	end

	def destroy
		@article = Article.find(params[:id])
		@article.destroy

		redirect_to articles_path
	end
	 
	private
	  	def article_params
	    	params.require(:article).permit(:title, :text)
	  	end
end

blog/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

blog/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_path, notice: "Signed In!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path,notice: "Signed out!"
  end
end

blog/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
	
	def show
	  @user = User.find(params[:id])
	end

end

blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

blog/app/helpers/home_helper.rb
module HomeHelper
end

blog/app/helpers/welcome_helper.rb
module WelcomeHelper
  	def correct_user(user)
		user != current_user
	end
end

blog/app/views/articles/edit.html.erb
<h1>Editing article</h1>

<% if correct_user(@user) %>
 
  <%= form_for :article, url: article_path(@article), method: :patch do |f| %>
   
    <% if @article.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@article.errors.count, "error") %> prohibited
          this article from being saved:
        </h2>
        <ul>
          <% @article.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
   
    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>
   
    <p>
      <%= f.label :text %><br>
      <%= f.text_area :text %>
    </p>
   
    <p>
      <%= f.submit %>
    </p>
   
  <% end %>
   
  <%= link_to 'Back', articles_path %>

  
<% end %>

blog/app/views/articles/index.html.erb
<h1>Listing articles</h1>

<% if correct_user(@user) %>

 
  <%= link_to 'New article', new_article_path %>

  <table>
    <tr>
      <th>Title</th>
      <th>Text</th>
    </tr>
   
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.text %></td>
        <td><%= link_to 'Show', article_path(article) %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article_path(article),
                method: :delete,
                data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </table>

  <% end %>

blog/app/views/articles/new.html.erb
<h1>Holla News</h1>

<% if currect_user(@user) %>

  <%= form_for :article, url: articles_path do |f| %>

    

  	<p>
  		<%= f.label :title %> <br>
  		<%= f.text_field :title %>
  	</p>

  	<p>
      	<%= f.label :text %><br>
      	<%= f.text_area :text %>
    	</p>

    	<p>
      	<%= f.submit %>
    	</p>
  <% end %>

  <%= link_to 'Back', articles_path %>

<% end %>

blog/app/views/articles/show.html.erb
<% if  correct_user(@user) %>
	<H1> See your article : </H1>
	<p>
	  <strong>Title:</strong>
	  <%= @article.title %>
	</p>
	 
	<p>
	  <strong>Text:</strong>
	  <%= @article.text %>
	</p>

	<%= link_to 'Back', articles_path %>
	<% else %>
		<H1> Want to see your article: Sign up ! </H1>
<% end %>

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Newsly Google Authentication</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div>
      <% if current_user %>
        Signed in as <strong><%= current_user.name %></strong>!
        <%= link_to "Sign out", signout_path, id: "sign_out" %>
      <% else %>
        <%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %>
      <% end %>
    </div>
    <div>
    <%= yield %>
    </div>
  </body>
</html>

blog/app/views/welcome/index.html.erb
<h1>Hey man</h1>

<% if correct_user(@user) %>
  <%= link_to 'New Article', controller: 'articles' %>
<% end %>